[package]
name = "chunked-quote-impl"
description = "quote using only one TokenStream"
version = "0.1.2"
edition = "2024"
readme = "../readme.md"
license = "MIT"
repository = "https://github.com/aliibrahim123/chunked-quote.rs"
documentation = "https://docs.rs/chunked-quote/"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.107"
quote = "1.0.47"
